### ISSUE TITLE
nitdoc: doc repeated on refinements

### ISSUE THREAD

**Issue by xymus** [privat/nit#1085]
Nitdoc repeats the doc of a method on each refinement, which makes it hard to read when there are multiple refinements that do not update the doc.

See: http://nitlanguage.org/doc/stdlib/class_app__app_base__App.html#app__app_base__App__init_window

**Comment by Morriar** [comment]
Hum... c'est lié à la dernière modif sur la sélection du commentaire. Quelques chose a du briser, je vais regarder.
