### ISSUE TITLE
New NativeString in FFI

### ISSUE THREAD

**Issue by R4PaSs** [privat/nit#1145]
There seems to be a problem either within FFI or with the way the `new` property of `NativeString` is defined in the Model, such that when using it in FFI, the compiler crashes with a `No provided declaration for NEW_standard__NativeString`.

Since the property is similar, I suspect `NativeArray` to behave similarly.

Here's an example of code that exposes this behaviour.

~~~nit
class A
        fun foo: NativeString import NativeString `{
                return new_NativeString(50);
        `}
end

var x = new A
var ns = x.foo
~~~

**Comment by privat** [comment]
@xymus can you look at it ?

**Comment by xymus** [comment]
This is a separate compiler issue actually, calling any extern constructors from extern code fails. I'm working on a fix. In the meantime, you can use the global compiler and it should be OK. (for new_NativeString at least).
