### ISSUE TITLE
Bootstrap on the Rasperry Pi

### ISSUE THREAD

**Issue by xymus** [privat/nit#1149]
I can't bootstrap the compiler on the Raspberry Pi because the c_src compiler requires libunwind, which is not available for arm under Debian Wheezy.

As a short term fix, I recommend to _not_ use libunwind in the c_src compiler. This will enable a partial bootstrap on the Raspberry Pi (and other similar platforms), and then we can compile the final compiler and other programs with explicitly no libunwind.

In the long term, the platform systems could manage this. But we will need to change the default platform when compiling the compiler. Maybe the makefile could mixin some code specific to the host platform?

**Comment by privat** [comment]
Can we add a Raspberry Pi to jenkins and track such a regression?

On Thu, Feb 5, 2015 at 10:35 PM, Alexis Laferrière <notifications@github.com

**Comment by xymus** [comment]
Probably... but even basic tests would be slow. I'm gonna give it a try.

**Comment by privat** [comment]
maybe just a specific job: the initial make and only some specific rpi
programs with rpi modules

On Thu, Feb 5, 2015 at 10:44 PM, Alexis Laferrière <notifications@github.com
