### ISSUE TITLE
Typo in first Github RPG achievement

### ISSUE THREAD

**Issue by xymus** [privat/nit#1165]
"First complain" should end with a t, complain is the verb. http://nitlanguage.org/rpg/games/privat/nit/achievements/player_1_issue

Where is the code of those achivements? I couldn't find it and fix it myself.

**Comment by privat** [comment]
And the associated issue should be indicated and linked.
And the first player to complain seems to be wrong

**Comment by Morriar** [comment]
@xymus nitlanguage.org/rpg is some PRs further thant the Git repo so I can beta test on a real project and see all these things :)
