### ISSUE TITLE
nitunit: execute nitunits in README.md of groups

### ISSUE THREAD

**Issue by xymus** [privat/nit#1201]
For a group `serialization` with a file `README.md`, launching `nitunit serialization` should detect and test the code snippets in the `README.md` file.

**Comment by privat** [comment]
Yeah, that assignee is just fine :)

**Comment by privat** [comment]
J'ai regardé rapidement . C'est assez compliqué et ça touche du code assez vieux et sale que j'ai écrit dans les premiers protos de nitunit. Je vais donc m'en occuper.

**Comment by privat** [comment]
closed by #1203
