### ISSUE TITLE
Nit doesn't use proper design patterns

### ISSUE THREAD

**Issue by jpcaissy** [privat/nit#1237]
Hi,

I'm trying to get my hands on Nit, but coming from a Java background I'm having difficulties with some design patterns that make Java such wonderful language.

You should refactor some of your code to make more usage of Singletons, Proxies, Factories and AbstractFactories.

This way, you'll get more traction from the software engineering! This will also help @Morriar's gamification system that just works™ , while @xymus could focus more on having Android builds working without memory leaks and @R4PaSs might be able to have real working unicode strings.

Thanks!

**Comment by jpcaissy** [comment]
cc @ppepos you really wanted that feature!

**Comment by R4PaSs** [comment]
Hi @jpcaissy,

This is actually a great idea !
For a long time I've been advocating the use of a Decorator pattern for the Stream hierarchy, Java's implementation of Files is simply amazing, I can't understand why we have not done it this way yet !

For singleton, we should really consider the introduction of a `static` keyword, ideally with a Java-like semantic !

**Comment by privat** [comment]
Design patterns are a deprecated technology of the last century; nowadays, modern things are the cloud computing, the internet of things, and business-oriented health care.

**Comment by privat** [comment]
Today, I wrote

~~~java
BufferedReader ir = new BufferedReader(new InputStreamReader(Files.newInputStream(Paths.get(args[i]))));
~~~

I was proud!
