### ISSUE TITLE
Bug in FileReader

### ISSUE THREAD

**Issue by budi-kurniawan** [privat/nit#1264]
FileReader.open(x) returns fewer than x characters even though EndOfFile has not been reached.

var fileReader = new FileReader.open(...)
for x in [0..4]
do
	var s = fileReader.read(4)
	print "{x}: {s.length}"
end
fileReader.close

Result:
4
4
2
4

Expected:
4
4
4
4

Note that in file.nit, the buffer is initially set to 10, which is why the third call to open(4) returns only 2 characters (the number of characters left in the buffer).

**Comment by privat** [comment]
Make sense. A non-full result should mean end of stream or end of current data (eg in a pipe or a tcp socket)  but not end of the internal buffer.
