### ISSUE TITLE
Binary operators

### ISSUE THREAD

**Issue by R4PaSs** [privat/nit#1271]
While we're on the subject of operators in view of v1, why don't we continue with the binary operators ?

Since we already have operators like `>>` and `<<` for bin_shifts, I'd suggest we add the remaining ones, namely:

* `&` for `bin_and`
* `|` for `bin_or`
* `^` for `bin_xor`
* `~` for `bin_not`

Maybe even their combination with an assignment as operators might be a valuable addition ?

**Comment by privat** [comment]
If related to #1267 it could make sense.

No other crazy operator requests guys?

**Comment by R4PaSs** [comment]
Yes, related to #1267 and #1262 since Unicode integration requires a lot of bitwise manipulations, this might help making the code more readable and remove parts that were written in C for cumberness (and a bit of performance-related fears) reasons.

**Comment by privat** [comment]
Question: What about being able to unarying all the binary operators (no only + and -)?
Good idea of bad idea?

**Comment by egagnon** [comment]
Interesting... So I could build a regular expression like ```x*```? Neat, but then I also want the concatenation binary operator ```x y```.

**Comment by R4PaSs** [comment]
I'm not against the possibility of having them, though I can hardly find a relevant example of such use for what are usually binary operators.

**Comment by privat** [comment]
@egagnon oh, I didn't think about that. I just thought about making only prefix unary operators since there is already 2 of them (+ and -) and a third one asked here by @R4PaSs (~). Currently, the only postfix operator is `[]` and it already has a special syntax.
Having both prefix and postfix operators will require to choose some global precedence in the grammar (and since + is prefix, it will be hard to justify that * is postfix).

For the empty operator, unfortunately this will make the grammar ambiguous I think, since we accept things like parenthesis-less calls, eg. `print hello`.

**Comment by privat** [comment]
@R4PaSs for instance, in C++, the prefix unary operator * is often used for dereference and the prefix unary operator & is often use for reference. Hum, suddenly this doesn't seem to be a good idea :)

**Comment by egagnon** [comment]
@privat I was having a little fun. There's the whole problem of operator precedence that shows up as soon as one wants to allow wide operator syntax. I don't think that it would be a good idea to stray too far from a very conservative and classical presentation of the few standard operators (+, -, *, ...) using fixed, predefined precedence and associativity.

**Comment by privat** [comment]
Unrelated to bitwise ops but some languages (python and eiffel at least if i remember correctly) have an integer division operator `//` (two slashes). Do you want it?
There is also the generalized sloppy comparator of ruby `===` (three equals). Or the pattern matching operator of perl `=~`.
Note: I am fine if you say that you do not want them :)

**Comment by egagnon** [comment]
The more operators you add, the more cryptic programs could become. Some programmers like to abuse operators.

Think of C++'s standard use of the shift operators  ```<<``` and ```>>``` for streams. Some people obviously like that. I don't.

**Comment by egagnon** [comment]
On the other extreme, you could look at APL which provided a very wide array of operators.

**Comment by R4PaSs** [comment]
@privat : Sure, I guess me being sick I forgot those elementary uses, and yes in this case I guess this is not such a good idea for Nit :)

Though I guess leaving the possibility to be redefined later in case someone has the use for it might be good idea ?
Why not leave the possibility for willing users to refine it should they need it for whatever purpose ?

Sure, there might be some bad uses of it all, but, regardless of whether we allow it or not, as you said

![](https://camo.githubusercontent.com/367fa5d7e8774de43541412a1430af84ae8192d3/687474703a2f2f692e696d6775722e636f6d2f436a69616b39622e6a7067)

As for the operators you proposed:

* `//` => What's the difference with a simple `/` when called on an Int ?
* `===` if the semantic's the same as JavaScript, I'm not at all convinced, it might be useful in a dynamic-typed language but in our case, I don't think it is appropriate
* `=~` this one I'll need explanation, is it some kind of sloppy equivalence operator ?

@egagnon : Ouch, APL is so brutal, I'm not sure we should even take a look at this :)
But I'll give it to them, the fact that they invented a keyboard for their needs proves their imagination !

**Comment by Morriar** [comment]
@R4PaSs In PERL, the `=~` and `=!` operators are used to pattern matching:

~~~perl
print "matches" if $myvar =~ /foo/;
print "does not match" if $myvar =! /foo/;
~~~

But I'm following @egagnon with the fact that this kind of operators will make the programs less readable.
