### ISSUE TITLE
syntax: Annotations

### ISSUE THREAD

**Issue by Morriar** [privat/nit#128]
To define an annotation on a class:

    class Foo annotation
         ...
    end

To define an annotation on a property:

    fun foo is annotation

Why there is no need of the "is" keyword for classes annotations?

    class Foo is annotation

Better looking if combined with an 'abstract' annotation:

    class Foo is abstract, annotation

Is there a SableCC grammar impossibility or something?

**Comment by privat** [comment]
closed by #1159
