### ISSUE TITLE
vim plugin: how to disable nit Omnifunc properly?

### ISSUE THREAD

**Issue by Morriar** [privat/nit#1300]
Hi,

Is there a way to disable the Nit Omnifunc behaviour but keep the standard Omnifunc?

I put this in my .vimrc:

~~~
" Disable nit omnifunc
autocmd FileType nit set omnifunc=syntaxcomplete#Complete
~~~

But the Nit Omnifunc stills appear!

The only way I found is to comment the line nit.vim.

**Comment by xymus** [comment]
There is no omnifunc by default in Vim. Maybe it comes from a plugin, or do you want to use the default autocompletion instead?

To deactivate the omnifunc it is:

~~~
autocmd FileType nit set omnifunc=''
~~~

**Comment by Morriar** [comment]
Yeah, I have this in my vimrc, that is supposed to enable the basic Omnifunc completion:

    autocmd FileType nit set omnifunc=syntaxcomplete#Complete

It is working with Ruby and other language. But it seems to be overriden by the Nit settings.
