### ISSUE TITLE
autoinit should not be accepted on an attribute with a default value

### ISSUE THREAD

**Issue by xymus** [privat/nit#1308]
~~~nit
class A
	var x = 0 is autoinit # There should be an error on the annotation
end

var a = new A
~~~

**Comment by privat** [comment]
In fact this is the feature #857; a non-pola feature that even I forgot about, but a feature nevertheless.

The `autoinit` on attribute with an initial value means that the initial value is computed at the autoinit step, thus enable a `autoinit` attribute to have a value that depend on the value of standard autoinit attributes.

~~~nit
class A
    var y: Int
    var x: Int = y + 1 is autoinit
end
var a = new A(10)
assert a.x = 11
~~~

Clearly, the feature should either be remover or made more pola.

**Comment by Morriar** [comment]
This is cool, maybe just add a warning when  the default value does not depend on another attribute?
