### ISSUE TITLE
nitunit: hanging indents on markdown lists recognized as code block

### ISSUE THREAD

**Issue by xymus** [privat/nit#1331]
In the following example, "2nd level 2nd line" is reported as an invalid Nit code block by nitunit. Both syntaxes used in the following example are legal according http://daringfireball.net/projects/markdown/syntax#list

Note that both syntax are supported correctly by nitdoc.

~~~
# Some title
#
# * 1st level.
# 1st level 2nd line # OK
#  * 2nd level.
#    2nd level 2nd line # Not OK
#  * Other 2nd level.
# Other 2nd level 2nd line # OK
fun foo do print "asdf"
~~~

As of now, we can use the alternative syntax for a simple case. However I do not see how to do multiple paragraph per point:

~~~
# Some title
#
# * 1st level.
#  * 2nd level.
#    2nd level 2nd line
#
#    2nd level 2nd paragraph # ?
fun foo do print "asdf"
~~~

From previous exchange, maybe the trigger for a code block should be 4 spaces more than the previous indent?

Bug encountered in #1323.

**Comment by Morriar** [comment]
Nice catch, nitunit is actually using the old md parser found in `docdown.nit`.

A rapid `git grep "import docdown"` gives us:
~~~
src/test_docdown.nit:20:import docdown
src/testing/testing_doc.nit:19:intrude import docdown
~~~

I propose to get rid of these parser and use the markdown lib as the rest of the Nit stack.

@privat: you were pretty attached to this parser, any objections?

**Comment by privat** [comment]
I did not remember that the old md parser was still used. You can scrap it as you wish.

**Comment by Morriar** [comment]
It was left as this to ensure compatibility with existing nitunit tests. A lot of existing docunits are not real markdown complient and thus, not tested.

I'm making the switch right now, let's see how many tests are missed.
