### ISSUE TITLE
Syntax and semantic of the range

### ISSUE THREAD

**Issue by privat** [privat/nit#1339]
The Nit range notation and semantic is very old and predate the current days where most modern languages offer a basic range type with a notation for literals.

Maybe some improvement can be done

## Syntax

* Nit `[1..5[` and `[1..5]`
* Ruby `1...5` and `1..5`
* Groovy `1..<5` and `1..5`
* Coffeescript `[1...5]` and `[1..5]`
* Python `range(1, 5)` (no inclusive range)
* Scala `(1 until 5)`  and `(1 to 5)`
* Swift `1..<5` and `1...5` (yes `...` for inclusive range, wtf!?)

## Range with steps

* Ruby: use a generator `1.step(4,2)` or `(1...5).step(2)`
* Python: `range(1,5,2)`
* Scala: `(1 until 5 by 2)`

## Reverse range

What is the behavior of `[10..5[` (or equivalent syntax)

Empty range: Nit, Ruby, Python
Reverse range: CoffeeScript

How to iterate in a reverse order?

* Ruby: use a generator `10.downto(6)`
* Python: use a negative step `range(10,5,-1)`
* Scala: use a negative step `(10 until 5 by -1)`
* Swift: use  `(10..<5).reverse()`

**Comment by Morriar** [comment]
I'm not sure of the intent of this issue. Are we wainting for the `TODO` parts?

**Comment by privat** [comment]
People that know languages can fill the todos.(and add languages)

The intent is about if we need to change how ranges are specified in nit.

**Comment by egagnon** [comment]
I like:
'''
[1..5[  # = 1,2,3,4
[1..5]  # = 1,2,3,4,5
[1..5] step 2  # = 1,3,5
[5..1] step -1 # = 5,4,3,2,1
]5..0] step -2 # = 4,2,0
'''
I didn't bother thinking about the lexical implications.

**Comment by Morriar** [comment]
@egagnon I like the `step` directive, this can be usefull.

Maybe pass this as an optional argument of the Range?

~~~nit
var r = [1..5, 2] # = 1, 3, 5
~~~

Better with named arguments:

~~~nit
var r = [1..5, step=2] # = 1, 3, 5
~~~

**Comment by egagnon** [comment]
I don't like ```step``` to be located within the range specification, as it breaks the ```[``` and ```]``` semantics:
```
[1..5, step=2[  # why is the "[" separated from the "5" it excludes? 
```

**Comment by Morriar** [comment]
@egagnon I'm not that chocked by your example. I think it makes sense.

**Comment by egagnon** [comment]
I still think that ```step``` outside is clearer and more intuitive.

Just forget about the lexer/parser mess, for a second, and look at it. Don't you find it simple and clean?
You could write:
```
var r = [0..10[ step 2  # 0,2,4,6,8
```
But, you can do what you want. I won't fight more about it.

**Comment by privat** [comment]
What about `step` being a method instead of a keyword?

~~~nit
var r = [0..10[.step(2)
~~~

**Comment by egagnon** [comment]
The method idea is really neat!

**Comment by R4PaSs** [comment]
I'd even say it's really Nit !

![](http://data2.whicdn.com/images/21382973/original.jpg)

Joke aside, yup I'm all for the method idea since @privat did not seem keen with the idea of sed'ing the few uses of step in the libs !

.step might be generalized in iterable collections then ? As a selector maybe ? With a positive step for the LTR iterator and a negative one for the RTL iterator (if available, an assert fail otherwise) ?

Maybe via an iterate method with a step as parameter ?

Something like

~~~nit
for i in "String".chars.iterate(1) do printn i # String
for i in "String".chars.iterate(-1) do printn i # gnirtS
~~~

**Comment by privat** [comment]
Discussion seems closed now
