### ISSUE TITLE
noautoinit annotation: strange behavior

### ISSUE THREAD

**Issue by Morriar** [privat/nit#1350]
I get something weird when using the `noautoinit` annotation.

Base code:

~~~nit
class Foo
	var a: Int
end

class Bar
	super Foo

	redef var a = 10
end

var foo = new Foo(230)
var bar = new Bar # error, normal
~~~

Here the last statement gives us the error:

> Error: expected 1 argument(s) for `init(a: Int)`; got 0. See introduction at `standard::Object::init`.

This is ok.

Now I try to clear the autinit list:

~~~nit
class Foo
	var a: Int
end

class Bar
        noautoinit
	super Foo

	redef var a = 10
end

var foo = new Foo(230)
var bar = new Bar # ok
~~~

Everything works well except that the compiler emit the following wanring:

> Warning: the list of autoinit is already empty. (useless-noautoinit)

**Comment by privat** [comment]
indeed; I will inversigate
