### ISSUE TITLE
Byte literals

### ISSUE THREAD

**Issue by R4PaSs** [privat/nit#1370]
Since we're trying to introduce a Byte type to nit in the near future, we need a way to express byte literals in the grammar.

But, there's actually no real syntax that seduces all of us, so here's a few propositions in here, if one seems acceptable I'll implement it, and if there's another idea that we have not yet thought of, please feel free to contribute to the issue !

# Suffix

The idea would be to suffix byte values with `b`, so that a numeric would look like

~~~nit
var x = 12b
assert x isa Byte
~~~

If this looks good enough for decimal numbers, we have an issue when dealing with Hexadecimal numbers:

~~~nit
# Do we mean 0x0F in Byte form or 0xFB in Int form ?
var x = 0xFb
~~~

One solution could be to force the use of decimal form for bytes, but since Bytes are often a bit magic or used to work on bit-level operations, I get the feeling that this is a bad idea...

# Prefix

Another idea that avoids the caveat of the Suffix would be to prefix bytes with `b`.

~~~nit
var x = b12
var y = b0xFb
~~~

This is quite practical, but I'm not that fond of the syntax personally, but I could live with it should we choose this approach.

# Cast

One approach that is chosen by a majority of languages with C-inspired syntax is to cast a number to byte to avoid any kind of ambiguity.

That or the static type of the variable is usually enough to determine the type, but we don't want that.

~~~nit
# x = 0xFB
var x = 0xFb.to_b
# y = 0xFF
var y = 0xFFF.to_b
~~~

This could be an approach, but with this we cannot have an overflow validation, though I guess that if you choose to input a number > 0xFF you're asking for the error.
But if we work with decimal numbers, this is a bit more surprising.

~~~nit
# x = 255
var x = -20.to_b
~~~

Performance-wise, since int.to_b is basically free, this should not be an issue.

# Annotation

Something that was suggested by @privat might be to use an annotation-based system to differentiate bytes and ints.

~~~nit
var x = 0xF@b
~~~

This is quite burdensome to read, but this would unambiguously differentiate ints and bytes.

# Length-based

Another idea would be to guess the type based on the bitwise length of the number entered.

~~~nit
var x = 128 # Byte
var y = 256 # Int
~~~

This could be an idea, but I feel that there could be surprises with this alternative, did we really want a Byte and not an Int in a particular case ?

# Other?

**Comment by jpages** [comment]
For the binary syntax I propose:
- use the syntax ```0b1010``` to write a binary: this is the Java syntax and I think this is kind of standard.
The prefix 0b indicates that the following number is written in binary (only 0 and 1).

I really like the proposal with ```to_b``` to convert any kind of representation to a binary one.

A few examples:
```128.to_b --> return a binary representation (and type) to 128 in decimal

0x15.to_b --> return a binary representation (and also type) of the hexadecimal 15 in binary
```

**Comment by R4PaSs** [comment]
A binary representation could be nice too, but this was not the issue at hand here :)

However, the fact that `to_b` could be mistaken from Byte to Binary does indeed bothers me, maybe we should call the proposed `to_b` `to_byte`.

Maybe I should be more specific when talking about Bytes, I meant the datatype analoguous to a C `unsigned char`, an 8-bit long data type that should be used when working at low-level.

But the possibility to express any number in the base that suits it the most might be discussed here too.

The binary `0b` is a good idea, for completeness's sake, we should probably introduce a way to express octal numbers too.

And in the octal case, the Java/C idiom of prefixing by 0 is imho really, really non-POLA.

Maybe a syntax similar to the `0x` in the form of `0o` could be introduced ?

**Comment by Morriar** [comment]
+1 for the `0b` and `0x`

**Comment by privat** [comment]
Suffix: ambiguity with hexadecimals is a problem, especially with bytes
Prefix: cause ambiguity with identifiers. `a0` `b0` `c0`, one is not like the other.
~~Cast~~ conversion method: non practical
Annotation: ugly, but does the job, but ugly
Length-based: not POLA
Other: F# use the `y` as a suffix (I do not know why). `11y == 3`

**Comment by R4PaSs** [comment]
The `y` is particularly strange, but why not.

Maybe a two-char token to avoid any ambiguity then ?

Maybe `UB` for Unsigned Byte ?

That would not be that bad then

~~~nit
# b == 0xF8
var b = 0xF8UB
~~~

**Comment by egagnon** [comment]
Why not the following suffixes:
```
u1, u2, u4, u8:  unsigned int of 1, 2, 4, and 8 bytes
s1, s2, s4, s8:  signed int of 1, 2, 4, and 8 bytes 
```
Or even better, go down to the bit level:
```
u8, u16, u32, u64:  unsigned int of 8, 16, 32, and 64 bits
s8, s16, s32, s64:  signed int of 8, 16, 32, and 64 bits
```
This would even allow for ```s30``` if one ever was tempted by tagged int objects.

What I don't like is that it exposes an assembly-language level of details.

**Comment by R4PaSs** [comment]
I'm not against the u8, u16 and such as suffixes, though we do not support arbitrary Int size for now, this would require all the subsequent Int derivatives to be implemented to be consistent with the proposal.

But all in all, this makes sense !

**Comment by privat** [comment]
I agree with @egagnon , u8 seems to be the better proposal for the moment (even if this low-level of details is very not nitish). Since it is to be used in very specific pieces of code, it is fine to me.

**Comment by R4PaSs** [comment]
Since both #1403 and #1410 solve the problem, I close this issue
