### ISSUE TITLE
Graph theory in Nit

### ISSUE THREAD

**Issue by ablondin** [privat/nit#1386]
Hi, everyone!

I'm currently working on a library for directed and undirected graphs. I would like to offer many basic services, such as computing the connected components, the strongly connected components, shortest paths, circuits, etc.

Before diving in completely, though, I would like to have your advice about what I have already done, especially concerning my design. The code is available in the branch https://github.com/ablondin/nit/tree/graphs.

Note that it depends on pull request #1384 (which is not merged yet), but except for that, the only files modified by it are those in the new directory `lib/graphs/`

The code is quite simple to understand. There are 3 classes:
* `AbstractDigraph`: the "mathematical" view of directed graphs. In other words, it will contains all methods about digraphs that are independent of the underlying data structures
* `HashMapDigraph`: this defines the basic operations on a graph (addition/removal/checking existence of vertices and edges, and adjacency) with HashMaps. It should be used in most of the cases.
* `ArrayDigraph`: this defines the basic operations with a 2D-array. It is expected to be more efficient in the case of dense graphs from which we do not remove vertices too often.

I don't want to make it a pull request, as it is clearly work in progress, but I think now is a good time to ask for your ideas. Any comment welcome!

**Comment by privat** [comment]
Nice. What about perfs? :)

**Comment by ablondin** [comment]
I haven't evaluated perfs yet, but I will very soon.
