### ISSUE TITLE
Loop unPOLA

### ISSUE THREAD

**Issue by R4PaSs** [privat/nit#1437]
So loop blocks are great, they allow the programmer to write the oh-so-infamous infinite loops.

As any infinite loop should go, we should be able to escape them anytime we'd like, via the good old `break` statement.

And oh was I surprised when I got this:

~~~nit
loop do
    break
end
print "x"
~~~

This yields an error at compile-time: `Error: unreachable statement. print "x"`

You got it, the `do end` is a simple block and the break escapes the block, not the loop, and the rest is history !

In all seriousness, maybe a warning should be raised when doing a `loop do` or the construction should be parsed as a loop block, not as a loop encompassing a block.

NOTE: Should it be tagged as `Bug` or as `It's not a bug, it's a feature` ?

**Comment by Morriar** [comment]
+1 for the bug label

**Comment by privat** [comment]
I do not remember why I created the label. #1392 maybe
