### ISSUE TITLE
Documentation for reverse loops

### ISSUE THREAD

**Issue by Bl4ckb0ne** [privat/nit#1495]
What's the quickest way to do this?
```C
for(i=length;i>1;i--) {
    foo
}
```

**Comment by R4PaSs** [comment]
Since #1397, the easiest would be a reversed range : 

~~~nit
for i in [length .. 1[.step(-1) do foo
~~~

**Comment by Bl4ckb0ne** [comment]
Thanks mate

**Comment by R4PaSs** [comment]
I'll leave it open since someone should add it to the manual to avoid such issues in the future

**Comment by Morriar** [comment]
I updated the issue title to be more relevant regarding the documentation.

**Comment by privat** [comment]
the specific doc if available here 

http://nitlanguage.org/doc/stdlib/class_standard__collection__range__Range.html#standard__collection__range__Range__step.definition

once nitdoc provide structure, we should be able to promote and make it more discoverable

**Comment by R4PaSs** [comment]
In the same way we promote forward `for` loops, we should provide a simple example of reversed `for` loops I think, on the [structue](http://nitlanguage.org/manual/structure/) page of the manual

**Comment by privat** [comment]
@R4PaSs just document it.

**Comment by R4PaSs** [comment]
Done

**Comment by privat** [comment]
missing proof https://github.com/nitlang/nitlanguage/commit/e102290141014c9437ff46d4c6a89052f4c8cc31
