### ISSUE TITLE
Autoinit issue

### ISSUE THREAD

**Issue by R4PaSs** [privat/nit#1552]
As the French say, "Jamais deux sans trois", here's a third issue on auto constructors and the autoinit annotation.

Suppose that in a module `t.nit`, we have:

~~~nit
class A
        var message: String

        var deux: nullable Bool = null is writable
end
~~~

In another module `test.nit`, we have:

~~~nit
import t

abstract class B
        var location: nullable Int
end
  
class C
        super A
        super B

        autoinit message, location
end
~~~

This time, I get an error: `Error: 'message' is not an autoinit method`

Note that the error only appears in this exact case, if classes A, B and C are reunited in a unique module, the problem disappears altogether

**Comment by privat** [comment]
The reason is that `message=` is private to `t.nit`, so invisible in `test.nit`.
This is a spec issue since the point of initializers is to be possibly combined in subclasses, thus having them private (invisible) by defaut is maybe a contradiction.
