### ISSUE TITLE
Bug with http://nitlanguage.org/tools/ ???

### ISSUE THREAD

**Issue by BlackMinou** [privat/nit#1593]
I'm not sure if it's normal but when you go to http://nitlanguage.org/ and try to go to the "Compiler and tools" section, the result page seems buged ( see http://nitlanguage.org/tools/ )

**Comment by Morriar** [comment]
Yup, seems like their is a bug with relative path resolution to the CSS file.

@privat seems to be related to #1505

**Comment by Morriar** [comment]
@BlackMinou maybe this could be moved to the right depo at https://github.com/nitlang/nitlanguage/issues

**Comment by privat** [comment]
fixed, it was an issue with the script that generate the manpages and deleted the `index.mdwn` file (ikiwiki do not put the index file at the same place)
