### ISSUE TITLE
FFI: instance collected to soon by garbage collector

### ISSUE THREAD

**Issue by Morriar** [privat/nit#1629]
This issue occurs with the [`mongodb.nit`](https://github.com/privat/nit/blob/master/lib/mongodb/mongodb.nit) wrapper.

In nit, the [`MongoCollection`](https://github.com/privat/nit/blob/master/lib/mongodb/mongodb.nit#L421) class is set as `finalizable` with the following `finalize` implementation:

~~~nit
	redef fun finalize do
		if is_alive then
			native.destroy
			is_alive = false
		end
	end
~~~

When calling [`MongoCollection::find`](https://github.com/privat/nit/blob/master/lib/mongodb/mongodb.nit#L601), the wrapper makes a call to `native.find`:

~~~nit
	fun find(query: JsonObject): nullable JsonObject do
		assert is_alive
		var c = native.find(query.to_bson.native) # <-- here
		if c == null then return null
		var cursor = new MongoCursor(c)
		if cursor.is_ok then
			cursor.next
			return cursor.item
		end
		return null
	end
~~~

Here is the [C implementation](https://github.com/privat/nit/blob/master/lib/mongodb/native_mongodb.nit#L424) that use's `self`:

~~~nit
	fun find(query: NativeBSON): nullable NativeMongoCursor import
		NativeMongoCursor.as nullable, set_mongoc_error `{
		bson_error_t error;
		mongoc_cursor_t	*cursor;
		cursor = mongoc_collection_find(self, MONGOC_QUERY_NONE, 0, 0, 0, query, NULL, NULL); // <-- here
		if (mongoc_cursor_error(cursor, &error)) {
			NativeMongoCollection_set_mongoc_error(self, &error);
			return null_NativeMongoCursor();
		}
		return NativeMongoCursor_as_nullable(cursor);
	`}
~~~

When running a complex program (cannot reproduce with just the API call), the `NativeCollection` instance is collected too soon thus resulting in a segfault:

~~~sh
Caught signal : Segmentation fault
-------------------------------------------------
--   Stack Trace   ------------------------------
-------------------------------------------------
` sig_handler
` killpg
` mongoc_read_prefs_copy
` _mongoc_cursor_new
` mongoc_collection_find
` native_mongodb___NativeMongoCollection_find___impl
` mongodb#NativeMongoCollection#find (/home/morriar/dev/projects/nit/lib/mongodb/native_mongodb.nit:416)
` mongodb#MongoCollection#find (/home/morriar/dev/projects/nit/lib/mongodb/mongodb.nit:580)
` nitrpg#GameStatsManager#load_stats_for (src/statistics.nit:100)
` nitrpg#GameStatsManager#overall (src/statistics.nit:85)
` nitrpg::test#standard::Sys#main (test.nit:4)
` main
` __libc_start_main
` _start
` 
-------------------------------------------------
Segmentation fault (core dumped)
~~~

I believe this problem is gc related because a quick fix consists in keeping a reference to self to avoid garbage collection:

~~~nit
	fun find(query: JsonObject): nullable JsonObject do
		assert is_alive
		var c = native.find(query.to_bson.native)
		assert is_alive # FIXME avoid garbage collection
		if c == null then return null
		var cursor = new MongoCursor(c)
		if cursor.is_ok then
			cursor.next
			return cursor.item
		end
		return null
	end
~~~

Here the most minimalist program I can give you that let the GC do his dark magic:

~~~nit
import nitrpg

var repo = api.load_repo("privat/nit")
assert repo != null
var game = new Game(api, repo)
game.db_name = "test"

var player = new Player(game, "Morriar")
var stats = player.stats
assert stats.overall["test"] == 0
~~~

**Comment by xymus** [comment]
Is the minimal program from a dev branch? If not, could you double check it? nitc doesn't find `nitrpg` (which I replaced with `web`), `api` or `db_name=`. I can tweak it to run but it doesn't do much.

**Comment by Morriar** [comment]
My bad, [here](https://github.com/Morriar/nit/tree/nitrpg-mongo) is the dev branch.

For the import you can use `import achievements` to get an more minimalist example that reproduce the crash.

**Comment by xymus** [comment]
The minimal program works on my machine using libbson and mongo-c-driver 1.1.10, none of the main structures are finalized. Do you use an older version of the libs?

Still, I noticed that in `native.find(query.to_bson.native)`, if I finalize/destroy `native` it works anyway and it only segfaults when finalizing the return of `query.to_bson`. The is superfluous wrapping and uwrapping of native objects in `query.to_bson.native` could be dangerous. Maybe gcc optimize out the reference to the return of `to_bson` before using `query.to_bson.native`.

Please try the following version, by not using a Nity wrapper and only the extern class it will not be finalized by the GC:
~~~
assert is_alive
var q = new NativeBSON.from_json_string(query.to_json.to_cstring)
var c = native.find(q)
q.destroy
if c == null then return null
# ...
~~~

**Comment by Morriar** [comment]
The version used are the 1.1.4 both on my computer and on pratchett.

I tried your fix. It works perfectly.

Thank you @xymus.
