### ISSUE TITLE
Default nit compilation directory

### ISSUE THREAD

**Issue by privat** [privat/nit#792]
The question that follow #789 is the default location of the .nit_compile directory.
The current working directory may not be the best place.

Some sensible choices are:

* in tmp (like gcc and other tools). But unlike gcc the name of the file must be stable to help ccache. However, /tmp is usually a ramdisk so better performances is a possible benefit.
* in ~ (or ~/.cache). So the user share its own stuff.
* in the root of the project (may not work if the owner is not the user)
* in the directory of the module (same issue)
* in the current working directory (status quo)
* in the current working directory but not hidden, and we name it `NIT_COMPILE_DIRECTORY_BEUAAARG` because we are proud

Other question, should nitg clean the directory after it? (with an optional --no-clean option for debugging the generated code)

**Comment by Morriar** [comment]
I'm more for the current directory with automatic cleaning after.

But my only argument is that I like to see what happened in my directory with `ls` when I use a new compiler.

**Comment by privat** [comment]
@Morriar the problem is that currently the build directory is hidden so that a `ls` will reveal you nothing without an additional `-a`
